### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by intkiran** [azlant/cra-template-redux-electron#1]
Please contact me for converting to create-react-app template, I am interested to do it

**Comment by azlant** [comment]
Sure, it's an existing cra template here, it just has those two issues I told you about. Happy to pay you for a PR?

**Comment by intkiran** [comment]
Please ping me here on skype: tokiran2

**Comment by intkiran** [comment]
please don't reply in CM

**Comment by intkiran** [comment]
Please don't reply in CM, it blocks my account

**Comment by intkiran** [comment]
my email id is ikiranbabu@gmail.com

**Comment by intkiran** [comment]
please give your email id

**Comment by intkiran** [comment]
please give your email id here, please don't comment in cmentor, it blocks my account

**Comment by intkiran** [comment]
Is your issue resolved?

**Comment by azlant** [comment]
yes, thanks for asking.
